# Generated by Django 5.2.11 on 2026-02-27 17:56

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.UploadWithUUID('categories/icons')),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.UploadWithUUID('categories/images')),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnall',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.UploadWithUUID('projects/thumbnails')),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.UploadWithUUID('technologies/icons')),
        ),
    ]
