# Generated by Django 5.2.11 on 2026-02-27 18:01

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_category_icon_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Tamanho recomendado/obrigatório: 64x64px.', null=True, upload_to=portfolio.models.UploadWithUUID('categories/icons'), validators=[portfolio.models.ImageDimensionsValidator(64, 64, 'Ícone da categoria')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Tamanho recomendado/obrigatório: 1200x630px.', null=True, upload_to=portfolio.models.UploadWithUUID('categories/images'), validators=[portfolio.models.ImageDimensionsValidator(1200, 630, 'Imagem da categoria')]),
        ),
    ]
