# Generated by Django 5.2.11 on 2026-02-27 18:07

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_category_icon_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(help_text='Tamanho recomendado/obrigatório: 64x64px.', null=True, upload_to=portfolio.models.UploadWithUUID('categories/icons'), validators=[portfolio.models.ImageDimensionsValidator(64, 64, 'Ícone da categoria')]),
        ),
    ]
