# Generated by Django 5.2.11 on 2026-02-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, help_text='Informe o ícone do react-icons no formato "di/DiDjango" ou "si/SiReact".', max_length=60, null=True),
        ),
    ]
