# Generated by Django 5.2.11 on 2026-02-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_technology_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('formation_type', models.CharField(choices=[('technologist', 'Tecnólogo'), ('graduation', 'Graduação'), ('postgrad', 'Pós-graduação'), ('professional_course', 'Curso profissionalizante'), ('certification', 'Certificação')], max_length=30)),
                ('institution', models.CharField(max_length=180)),
                ('area', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_in_progress', models.BooleanField(default=False)),
                ('workload_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-featured', 'order', '-start_date', '-created'],
            },
        ),
    ]
