# Generated by Django 5.2.11 on 2026-02-28 12:00

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_contactsubject_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="Sobre Mim", max_length=150)),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem principal da seção Sobre Mim.",
                        null=True,
                        upload_to=portfolio.models.UploadWithUUID("about"),
                    ),
                ),
            ],
            options={
                "ordering": ["-update", "-created"],
            },
        ),
    ]
