# Generated by Django 5.2.11 on 2026-03-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_aboutcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('budget_range', models.CharField(choices=[('up_to_1k', 'Até R$ 1.000'), ('1k_to_5k', 'R$ 1.000 - R$ 5.000'), ('5k_to_10k', 'R$ 5.000 - R$ 10.000'), ('10k_to_20k', 'R$ 10.000 - R$ 20.000'), ('above_20k', 'Acima de R$ 20.000')], max_length=20)),
                ('timeline', models.CharField(choices=[('1_week', '1 semana'), ('2_3_weeks', '2-3 semanas'), ('1_2_months', '1-2 meses'), ('2_3_months', '2-3 meses'), ('over_3_months', 'Mais de 3 meses')], max_length=20)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('under_review', 'Em análise'), ('proposal_sent', 'Proposta enviada'), ('rejected', 'Rejeitado')], default='new', max_length=20)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='portfolio.contactsubject')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
