# Generated by Django 5.2.11 on 2026-03-02 14:23

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.UploadWithUUID('service-requests/logos')),
        ),
    ]
