# Generated by Django 5.2.11 on 2026-03-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_servicerequest_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='timeline',
        ),
    ]
