# Generated by Django 5.2.11 on 2026-03-02 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_servicerequest_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='privacy_consent',
            field=models.BooleanField(default=False, help_text='Indica se o usuário consentiu com a Política de Privacidade (LGPD)'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='privacy_consent_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Data e hora em que o consentimento foi registrado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='privacy_policy_version',
            field=models.CharField(default='1.0', help_text='Versão da Política de Privacidade aceita pelo usuário', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='privacy_consent',
            field=models.BooleanField(default=False, help_text='Indica se o usuário consentiu com a Política de Privacidade (LGPD)'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='privacy_consent_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Data e hora em que o consentimento foi registrado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='privacy_policy_version',
            field=models.CharField(default='1.0', help_text='Versão da Política de Privacidade aceita pelo usuário', max_length=20),
        ),
    ]
