# Generated by Django 5.2.11 on 2026-03-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_contactmessage_privacy_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='privacy_consent_date',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o consentimento foi registrado', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='privacy_consent_date',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o consentimento foi registrado', null=True),
        ),
    ]
