# Generated by Django 5.2.11 on 2026-03-04 00:29

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_contactmessage_privacy_consent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='brand_identity_status',
            field=models.CharField(blank=True, choices=[('manual', 'Sim, tenho manual da marca'), ('logo_only', 'Tenho apenas a logo'), ('none', 'Ainda não tenho identidade visual')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='brand_manual_file',
            field=models.FileField(blank=True, null=True, upload_to=portfolio.models.UploadWithUUID('service-requests/brand-manuals')),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('unknown', 'Ainda não sei'), ('1k_3k', 'R$ 1k – 3k'), ('3k_8k', 'R$ 3k – 8k'), ('8k_20k', 'R$ 8k – 20k'), ('20k_plus', 'Acima de R$ 20k')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='reference_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='timeline',
            field=models.CharField(blank=True, choices=[('no_rush', 'Sem pressa'), ('1_month', '1 mês'), ('2_3_months', '2–3 meses'), ('more_than_3_months', 'Mais de 3 meses'), ('urgent', 'Urgente')], max_length=25, null=True),
        ),
    ]
